import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get_utils/src/extensions/internacionalization.dart';

Widget doctorDetails() {
  return ListWheelScrollView(
    itemExtent: 300,
    children: [
      Text(
        "terms_and_conditions".tr,
        textAlign: TextAlign.center,
        style: TextStyle(fontSize: 20.sp, color: Colors.blue[700]),
      ),
      Text("subtitle_conditions_p1".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p2".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p3".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p4".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p5".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p6".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p7".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p8".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p9".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p10".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p11".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p12".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p13".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p14".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p15".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_conditions_p16".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
    ],
  );
}
