import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get_utils/src/extensions/internacionalization.dart';

List _useSpot = [
  {"title": "use_app_p1".tr, "subtitle": "".tr},
  {"title": "use_app_p2".tr, "subtitle": "subtitle_use_app_p2".tr},
  {"title": "use_app_p3".tr, "subtitle": "subtitle_use_app_p3".tr},
  {"title": "use_app_p4".tr, "subtitle": "subtitle_use_app_p4".tr},
  {"title": "use_app_p5".tr, "subtitle": "subtitle_use_app_p5".tr},
  {"title": "use_app_p6".tr, "subtitle": "subtitle_use_app_p6".tr},
  {"title": "use_app_p7".tr, "subtitle": "subtitle_use_app_p7".tr},
  {"title": "use_app_p8".tr, "subtitle": "subtitle_use_app_p8".tr},
];
Widget UseSpotApp() {
  return ListWheelScrollView(
    itemExtent: 300,
    children: [
      Text(
        "screen_info".tr,
        textAlign: TextAlign.center,
        style: TextStyle(fontSize: 20.sp, color: Colors.blue[700]),
      ),
      Text("subtitle_screen_info1".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_screen_info2".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_screen_info3".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_screen_info4".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_screen_info5".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_screen_info6".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_screen_info7".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text("subtitle_screen_info8".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text(
        "use_app_p1".tr,
        textAlign: TextAlign.center,
        style: TextStyle(fontSize: 20.sp, color: Colors.blue[700]),
      ),
      Text("subtitle_use_app_p1".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text(
        "use_app_p2".tr,
        textAlign: TextAlign.center,
        style: TextStyle(fontSize: 20.sp, color: Colors.blue[700]),
      ),
      Text("subtitle_use_app_p2".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text(
        "use_app_p3".tr,
        textAlign: TextAlign.center,
        style: TextStyle(fontSize: 20.sp, color: Colors.blue[700]),
      ),
      Text("subtitle_use_app_p3".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text(
        "use_app_p4".tr,
        textAlign: TextAlign.center,
        style: TextStyle(fontSize: 20.sp, color: Colors.blue[700]),
      ),
      Text("subtitle_use_app_p4".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text(
        "use_app_p5".tr,
        textAlign: TextAlign.center,
        style: TextStyle(fontSize: 20.sp, color: Colors.blue[700]),
      ),
      Text("subtitle_use_app_p5".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text(
        "use_app_p6".tr,
        textAlign: TextAlign.center,
        style: TextStyle(fontSize: 20.sp, color: Colors.blue[700]),
      ),
      Text("subtitle_use_app_p6".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text(
        "use_app_p7".tr,
        textAlign: TextAlign.center,
        style: TextStyle(fontSize: 20.sp, color: Colors.blue[700]),
      ),
      Text("subtitle_use_app_p7".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
      Text(
        "use_app_p8".tr,
        textAlign: TextAlign.center,
        style: TextStyle(fontSize: 20.sp, color: Colors.blue[700]),
      ),
      Text("subtitle_use_app_p8".tr,
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 15.sp, color: Colors.blueGrey[900])),
    ],
  );
}
